### ISSUE TITLE
Buying Glitch

### ISSUE THREAD

**Issue by jacobt6y** [shiftosnext/shiftos-next#4]
So I Have Tried To Purchase Basic Custom Shade And It Wont Let Me Download Basic Custom Shade
And I Have Enough Code Points But It Wont Let Me Select It Or Download It.

**Comment by TheUltimateHacker** [comment]
This is because that upgrade isn't implemented yet. It is, however, buyable, but has no purpose as of yet, but you won't need to download that upgrade. However, thanks for letting me know!

**Comment by RandomMelon** [comment]
Has this seriously not been closed yet? Wow. OK, issue closed.
