### ISSUE TITLE
Simple Typ-o

### ISSUE THREAD

**Issue by AShifter** [shiftosnext/shiftos-next#6]
I just found a typ-o. 
![dhiftos](https://cloud.githubusercontent.com/assets/10788034/8393864/2cbde728-1cdf-11e5-8866-dbd33d6a9128.png)

**Comment by TheUltimateHacker** [comment]
Wow, I never even noticed that and I've been pulling out releases... lol

**Comment by RandomMelon** [comment]
This issue has been noticed and will be fixed, issue closed.
