### ISSUE TITLE
MDE Starting Issue

### ISSUE THREAD

**Issue by areno2002** [shiftosnext/shiftos-next#7]
After I bought all upgrades, when I attempt to run: "test mde" on ShiftOS-Next 0.0.2 Alpha 1, I get this error:

Cannot find part of the path
C:\ShiftOS\Shiftum42\MDE\Config\user.cfg

I don't have the folder: "MDE" in Shiftum42 at all, possible bug?

I think there is a problem generating that file, I hope this helped.

**Comment by TheUltimateHacker** [comment]
actually, the "test mde" command is obsolete. Try using "debugmode" and doing "test mdestory". That should get you to the MDE. It also creates the necessary files required to run the MDE, and that crash will not happen.

**Comment by RandomMelon** [comment]
Now that this "bug" is fixed, this issue is now closed. (P.S Michael, start closing issues that don't need any more comments.)
