### ISSUE TITLE
No SAVEHIERARCHY.DAT file

### ISSUE THREAD

**Issue by dragonexagon** [shiftosnext/shiftos-next#9]
"C:\Users\(me)\AppData\SAVEHIERARCHY.DAT" does not exist. did you misspell something, or in your style, fucked up?

**Comment by TheUltimateHacker** [comment]
Hmmm, must've fucked up xD... I'll check if it's in my Roaming or Local folder, who knows xD

**Comment by dragonexagon** [comment]
(waiting intensifies)

**Comment by TheUltimateHacker** [comment]
Alright, try in C:\Users\Michael\AppData\Roaming\shiftos_next\ShiftOS-Next\1.0.0.0.

Replace "Michael" with your username. If the file's not there you can copy your older SAVEHIERARCHY.DAT that was written to the same folder as your Alpha 3 executable to the new location. If you're playing from the source code though, you may have to recreate the file yourself. It's pretty easy, each line is just a hardcoded path to a save.
